name: realtime_chat
description: "A new Flutter project."


version: 1.0.0+1

environment:
  sdk: ^3.10.0-236.0.dev


dependencies:
  flutter:
    sdk: flutter 
  cupertino_icons: ^1.0.8
  web_socket_channel: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter 
  flutter_lints: ^6.0.0


flutter: 
  uses-material-design: true
 